name: flutter_application_7
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  firebase_core: ^2.30.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  firebase_database: ^10.4.5
  flutter_local_notifications: ^17.1.2
  vibration: ^1.7.5
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  