// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS5PwyqmuCuPoqRM8pXaPh_9OtxqqjyyA',
    appId: '1:171395486421:web:3c1b9dac5ab8ce0094c85c',
    messagingSenderId: '171395486421',
    projectId: 'smart-home-5e0d1',
    authDomain: 'smart-home-5e0d1.firebaseapp.com',
    databaseURL: 'https://smart-home-5e0d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-5e0d1.firebasestorage.app',
    measurementId: 'G-1N4CRKXYCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt3e_Pu_p-T9JEueWGXnOC4-HKiTDNMuY',
    appId: '1:171395486421:android:8caa0c2cdbaf904294c85c',
    messagingSenderId: '171395486421',
    projectId: 'smart-home-5e0d1',
    databaseURL: 'https://smart-home-5e0d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-5e0d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0ZrVA_0SYsDYZi1tYhljm-0Z30uVIxs',
    appId: '1:171395486421:ios:4bb66ec9637c3f3094c85c',
    messagingSenderId: '171395486421',
    projectId: 'smart-home-5e0d1',
    databaseURL: 'https://smart-home-5e0d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-5e0d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH0ZrVA_0SYsDYZi1tYhljm-0Z30uVIxs',
    appId: '1:171395486421:ios:4bb66ec9637c3f3094c85c',
    messagingSenderId: '171395486421',
    projectId: 'smart-home-5e0d1',
    databaseURL: 'https://smart-home-5e0d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-5e0d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS5PwyqmuCuPoqRM8pXaPh_9OtxqqjyyA',
    appId: '1:171395486421:web:47e836ea89eb1f8494c85c',
    messagingSenderId: '171395486421',
    projectId: 'smart-home-5e0d1',
    authDomain: 'smart-home-5e0d1.firebaseapp.com',
    databaseURL: 'https://smart-home-5e0d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-5e0d1.firebasestorage.app',
    measurementId: 'G-ERYRC4EEHG',
  );
}
